# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/will/Desktop/raycastsfml

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/will/Desktop/raycastsfml

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/will/Desktop/raycastsfml/CMakeFiles /home/will/Desktop/raycastsfml/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/will/Desktop/raycastsfml/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named raycastsfml

# Build rule for target.
raycastsfml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 raycastsfml
.PHONY : raycastsfml

# fast build rule for target.
raycastsfml/fast:
	$(MAKE) -f CMakeFiles/raycastsfml.dir/build.make CMakeFiles/raycastsfml.dir/build
.PHONY : raycastsfml/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/raycastsfml.dir/build.make CMakeFiles/raycastsfml.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/raycastsfml.dir/build.make CMakeFiles/raycastsfml.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/raycastsfml.dir/build.make CMakeFiles/raycastsfml.dir/main.cpp.s
.PHONY : main.cpp.s

map.o: map.cpp.o

.PHONY : map.o

# target to build an object file
map.cpp.o:
	$(MAKE) -f CMakeFiles/raycastsfml.dir/build.make CMakeFiles/raycastsfml.dir/map.cpp.o
.PHONY : map.cpp.o

map.i: map.cpp.i

.PHONY : map.i

# target to preprocess a source file
map.cpp.i:
	$(MAKE) -f CMakeFiles/raycastsfml.dir/build.make CMakeFiles/raycastsfml.dir/map.cpp.i
.PHONY : map.cpp.i

map.s: map.cpp.s

.PHONY : map.s

# target to generate assembly for a file
map.cpp.s:
	$(MAKE) -f CMakeFiles/raycastsfml.dir/build.make CMakeFiles/raycastsfml.dir/map.cpp.s
.PHONY : map.cpp.s

player.o: player.cpp.o

.PHONY : player.o

# target to build an object file
player.cpp.o:
	$(MAKE) -f CMakeFiles/raycastsfml.dir/build.make CMakeFiles/raycastsfml.dir/player.cpp.o
.PHONY : player.cpp.o

player.i: player.cpp.i

.PHONY : player.i

# target to preprocess a source file
player.cpp.i:
	$(MAKE) -f CMakeFiles/raycastsfml.dir/build.make CMakeFiles/raycastsfml.dir/player.cpp.i
.PHONY : player.cpp.i

player.s: player.cpp.s

.PHONY : player.s

# target to generate assembly for a file
player.cpp.s:
	$(MAKE) -f CMakeFiles/raycastsfml.dir/build.make CMakeFiles/raycastsfml.dir/player.cpp.s
.PHONY : player.cpp.s

raycaster.o: raycaster.cpp.o

.PHONY : raycaster.o

# target to build an object file
raycaster.cpp.o:
	$(MAKE) -f CMakeFiles/raycastsfml.dir/build.make CMakeFiles/raycastsfml.dir/raycaster.cpp.o
.PHONY : raycaster.cpp.o

raycaster.i: raycaster.cpp.i

.PHONY : raycaster.i

# target to preprocess a source file
raycaster.cpp.i:
	$(MAKE) -f CMakeFiles/raycastsfml.dir/build.make CMakeFiles/raycastsfml.dir/raycaster.cpp.i
.PHONY : raycaster.cpp.i

raycaster.s: raycaster.cpp.s

.PHONY : raycaster.s

# target to generate assembly for a file
raycaster.cpp.s:
	$(MAKE) -f CMakeFiles/raycastsfml.dir/build.make CMakeFiles/raycastsfml.dir/raycaster.cpp.s
.PHONY : raycaster.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... raycastsfml"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... map.o"
	@echo "... map.i"
	@echo "... map.s"
	@echo "... player.o"
	@echo "... player.i"
	@echo "... player.s"
	@echo "... raycaster.o"
	@echo "... raycaster.i"
	@echo "... raycaster.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

